### ISSUE TITLE
Agregar Proyecto propio 

### ISSUE THREAD

**Issue by fgonzalezurriola** [Nyveon/open-source-uchile#1]
**Descripción del Recurso:**
Web para ver la malla de algunas carreras de la FCFM

**Link del item:**
https://mallas-fcfm-fgonzalezurriola.vercel.app/

**Contexto adicional:**
.

Texto completo a agregar sugerido markdown
- [Mallas-fcfm-fgonzalezurriola](https://mallas-fcfm-fgonzalezurriola.vercel.app/) - Visualización de algunas mallas de la FCFM con prerrequisitos.

**Comment by Nyveon** [comment]
Está bacán tu página!!! Gracias por compartirlo

Ahí lo agregué a la lista c:
