### ISSUE TITLE
Malla Interactiva DCC (y más en un futuro)

### ISSUE THREAD

**Issue by MikaGaete** [Nyveon/open-source-uchile#2]
**Descripción del Recurso:**
Malla interactiva que permite marcar y guardar el avance en la carrera que además muestra los pre-requisitos de cada ramo y los ramos disponibles según el avance actual.

**Link del item:**
Pagina web: https://mallas.mikael.cl/, Repositorio: https://github.com/MikaGaete/MallaInteractivaFCFM.git

**Contexto adicional:**
N/A

**Comment by Nyveon** [comment]
Está super bueno! c:

Ahí lo agregué a la lista
