### ISSUE TITLE
Agregar proyecto :p

### ISSUE THREAD

**Issue by AyanoT1** [Nyveon/open-source-uchile#3]
Descripción del Recurso:
Web de busqueda de información de ramos DCC, basado en la herramienta ya existente del CaDCC ramos.cadcc.cl. In a nutshell es una nueva interfaz con las features claves, filtrado y busqueda por input y (casi) los mismos datos.

Link del item:
Pagina web: [ayanot1.github.io/search-tool-ramosDCC/](https://ayanot1.github.io/search-tool-ramosDCC/) , Repositorio: https://github.com/AyanoT1/search-tool-ramosDCC

Contexto adicional:
N/A

**Comment by Nyveon** [comment]
Está bacán el proyecto! Agregado c:

(Ajuste la descripción para que sea solo una oración, si prefieres que se redacte de otra manera me avisas no más)
